### PR TITLE
several design dashboard map

### LINKED ISSUE #92: media query for the size of the backoffice's map
Set up several css media queries to adapt the size of the map to the size of the user's screen

depends on #91

### PR DESCRIPTION
**Pull request by M4rtine**
media queries for map size
best integration map in design

Fixed #92

### CODE REVIEW

**Comment by foutoucour** [comment]
It is fine on my imac
screen shot 2015-05-13 at 10 50 40 am

**Comment by M4rtine** [comment]
I think i keep adjust with a better scss way

**Comment by M4rtine** [comment]
Fixed #92

**Comment by foutoucour** [comment]
The map is now at a good size but the map_info overlay is at the top left corner instead of bottom left corner. :-1:

**Comment by M4rtine** [comment]
I mad it in order to place this popup in the only position which is not
responsive. Besides bottom left is not a logical position when you are
clicking on something which do appear some information.

—
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/pull/102#issuecomment-101767644>
> .
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by foutoucour** [comment]
Ok then.
But could you move it a bit as it is over the zoom widget?

**Comment by M4rtine** [comment]
ok sorry i think that controls of map will be hidden 
i Will fixed that

**Comment by M4rtine** [comment]
map_infobox position Fixed #92 
@foutoucour

**Comment by foutoucour** [comment]
:+1:

**Pull request merged**
