### PR TITLE
update colors and logo Design

### PR DESCRIPTION
**Pull request by M4rtine**
compared to graphical identity
favicons full compatibility

updating files :
- color.scss
- cgstudiomap.svg
- company_details.xml
- create folder "fav"
- all favicons assets
- web_layout.xml

### CODE REVIEW

**Comment by foutoucour** [comment]
This is related to #32 

Here are screenshots of the update:
screen shot 2015-04-28 at 4 45 11 pm

screen shot 2015-04-28 at 4 45 40 pm

screen shot 2015-04-28 at 4 46 20 pm

screen shot 2015-04-28 at 4 46 36 pm

screen shot 2015-04-28 at 4 48 27 pm

**Comment by foutoucour** [comment]
My feedback: 
1. I don't know if the color of the pointer on the map are easy to read. To close to the color of the sea maybe
2. The color of the required fields should be changed to be easier to read
3. Like it! I need to find the css related to the tags tho.
4. Home-page looks good to me.
5. The list view is cool also.

**Comment by foutoucour** [comment]
Unfortunately, svg are not working for the logo of the company. Only images are accepted :(

**Comment by M4rtine** [comment]
Yes we can adjust more. Errors is mostly due to my variables identification. I myst do better.
And i will work better when my install will be done

Favicon is it good?

**Comment by M4rtine** [comment]
Background of homepage & the listing of studios is more complex too.
i must find where it is.

**Comment by foutoucour** [comment]
Screenshot of the new approach.
We figured out that we won't have time to find the good colors before the release of the milestone, then we are going to use grays for now.

screen shot 2015-04-30 at 3 00 46 pm

**Comment by foutoucour** [comment]
@M4rtine need the favicon set in gray please

**Comment by M4rtine** [comment]
Done ;)

**Comment by foutoucour** [comment]
Page of sign up during the private alpha phase.
screen shot 2015-05-02 at 3 58 33 pm

The page is here to inform the user he can't register to the website by himself for now.
I want to have this page so the user is aware about what we are doing.
@M4rtine do you want to redo the page?

**Comment by foutoucour** [comment]
Rough new design for the map_info 

screen shot 2015-05-02 at 4 45 32 pm

**Comment by M4rtine** [comment]
Signup page =
- put the complete logo with name 
- text must be less contrast and link more contrast.
- "the team" less less contrast like the actual link

map studio info =
- "more" it is an important link, so it must looks like badge, or sidebar link in dashboard (dark bg with light text)
- i think complete adress is not important here.  we could remove all titles (adress, city, zip...). 
Studio name more larger and under only the summary adress ( for example  Montreal, CANADA ou Paris, FRANCE) What do you think about keep focus usées to studio id card ?

**Comment by foutoucour** [comment]
Logo in gray for milestone 0.1

**Pull request closed without merging**
