### PR TITLE
97 map border color

### LINKED ISSUE #97: Homepage map: border colors
Following #95 a color for borders has to be set.

### PR DESCRIPTION
**Pull request by M4rtine**
update colors
add border
update bg color

Fixed #97

### CODE REVIEW

**Comment by foutoucour** [comment]
looks good:


But 2 points:
* Why did you turn it to yellow? Isn't blue the color of the map?
* The scroll bar is gone again :(

**Comment by M4rtine** [comment]
we don't have the final Colors because graphic identity is not finished. i think grey colors is for studying the impact of UI with no colors engagment.
Yellow is a natural tonic color for professional feeling.

**Comment by M4rtine** [comment]
i don't know why the scroll is hidden i will check that.

**Comment by M4rtine** [comment]
Scroll fixed #97

**Pull request merged**
